apiVersion: external-secrets.io/v1beta1
kind: ClusterExternalSecret
metadata:
  name: vault-example-cluster
spec:
  namespaceSelector:
    matchLabels: 
      cool: label
  refreshTime: "1m"
  externalSecretSpec:
    secretStoreRef:
      name: vault-backend-cluster
      kind: ClusterSecretStore
    target:
      name: vault-sync
    data:
    - secretKey: secret_value
      remoteRef:
        key: path/to/my/secret
        property: cowsay